// <auto-generated />
using System;
using EmployeeManagement.Api.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240819044714_Initials")]
    partial class Initials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManagement.Model.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Account"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Marketing"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateofBirth = new DateTime(2024, 8, 19, 10, 47, 14, 171, DateTimeKind.Local).AddTicks(7829),
                            DepartmentId = 1,
                            Email = "Rana@gmail.com",
                            FirstName = "Reazul Islam",
                            Gender = 0,
                            LastName = "Rana",
                            PhotoPath = "Images/img10.jpg"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateofBirth = new DateTime(2024, 8, 19, 10, 47, 14, 173, DateTimeKind.Local).AddTicks(5904),
                            DepartmentId = 1,
                            Email = "Moushumee@gmail.com",
                            FirstName = "Moushumee",
                            Gender = 1,
                            LastName = "Mollika",
                            PhotoPath = "Images/img11.jpg"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateofBirth = new DateTime(2024, 8, 19, 10, 47, 14, 173, DateTimeKind.Local).AddTicks(5937),
                            DepartmentId = 1,
                            Email = "Ibrahim@gmail.com",
                            FirstName = "Ibrahim Rihan",
                            Gender = 0,
                            LastName = "Ayat",
                            PhotoPath = "Images/img12.jpg"
                        },
                        new
                        {
                            EmployeeId = 4,
                            DateofBirth = new DateTime(2024, 8, 19, 10, 47, 14, 173, DateTimeKind.Local).AddTicks(5944),
                            DepartmentId = 1,
                            Email = "Milon@gmail.com",
                            FirstName = "Milon",
                            Gender = 0,
                            LastName = "Ahmed",
                            PhotoPath = "Images/img9.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
